export enum TransferAction {
    CREATE = 'CREATE',
    ACTIVATE = 'ACTIVATE',
    DEACTIVATE = 'DEACTIVATE',
    CANCEL = 'CANCEL',
    PACK = 'PACK',
    PACKED = 'PACKED',
    START_DELIVERY = 'START_DELIVERY',
    DELIVERED = 'DELIVERED',
    START_RECEIVE = 'START_RECEIVE',
    RECEIVED = 'RECEIVED',
    RETURN = 'RETURN',
    RETURNED = 'RETURNED',
}
