image: node:latest

default:
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

stages:
  - lint
  - test
  - release

lint:commit:
  stage: lint
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
    - npm run lint

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test
    - npm run test:e2e
    - npm run test:cov
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml

release:
  stage: release
  before_script:
    - cp .gitlab/npmrc .npmrc
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"