image: node:latest

before_script:
  - npm ci --cache .npm --prefer-offline
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

stages:
  - lint
  - test
  - release

lint:commit:
  stage: lint
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

lint:code:
  stage: lint
  script:
    - ./node_modules/eslint/bin/eslint.js $(git diff --name-only HEAD | grep -E 'src/.*\.ts|test/.*\.ts$' | xargs)

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - MIKRO_ORM_CLI=./config/mikro-orm.test.config.ts npx mikro-orm cache:generate --ts
    - npm run test:cov
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

release:
  stage: release
  before_script:
    - cp .gitlab/npmrc .npmrc
  script:
    - ./node_modules/semantic-release/semantic-release.js
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
