image: node:latest

default:
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - dist/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}
  MIKRO_ORM_CLI: ${MIKRO_ORM_CLI}

stages:
  - lint
  - test
  - release

lint:commit:
  stage: lint
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

lint:code:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  before_script:
    - npm install
    - npx mikro-orm cache:generate
  script:
    - npm run test:cov
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

release:
  stage: release
  before_script:
    - cp .gitlab/npmrc .npmrc
  script:
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/git @semantic-release/npm
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
