image: node:latest

default:
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

stages:
  - test
  - release

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm run test

release:
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/git @semantic-release/npm
    - cp .gitlab/npmrc .npmrc
  script:
    - semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"